# File: .github/workflows/run-integration-tests.yml
name: Run Integration Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        agent: ["SWEAgent", "PlannerAgent", "MonologueAgent", "CodeActAgent"]
        sandbox: ["ssh", "exec"]
        include:
          - agent: "MonologueAgent"
            embedding-model: "local"
          - agent: "MonologueAgent"
            sandbox: "local"
            embedding-model: "local"
          - agent: "SWEAgent"
            embedding-model: "none"
          - agent: "PlannerAgent"
            embedding-model: "none"
          - agent: "CodeActAgent"
            embedding-model: "none"
    steps:
      - uses: ./.github/workflows/setup-environment.yml
        with:
          operating-system: ubuntu-latest
          install-docker: true
          make-command: build
          install-dependencies: true
      - name: Run Integration Tests
        env:
          SANDBOX_TYPE: ${{ matrix.sandbox }}
          AGENT: ${{ matrix.agent }}
          MAX_ITERATIONS: 10
          LLM_EMBEDDING_MODEL: ${{ matrix.embedding-model }}
        run: |
          rm -rf workspace
          mkdir workspace
          WORKSPACE_BASE="$GITHUB_WORKSPACE/workspace" \
          WORKSPACE_MOUNT_PATH="$GITHUB_WORKSPACE/workspace" \
          poetry run pytest --cov=agenthub --cov=opendevin --cov-report=xml \
          -s ./tests/integration
